name: My First Workflow
on: push
jobs:
  My_first_job_:
    runs-on: ubuntu-latest
    steps:
      - name: create a file
        run: echo "Hello, World!" > hello.txt

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: hello-file
          path: hello.txt