name: My First Workflow
on: push
jobs:
  My_first_job_:
    runs-on: [self-hosted, linux, x64,b14]
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2

  My_second_job_:
    runs-on: ubuntu-latest
    needs: My_first_job_
    steps:
      - name: install npm
        uses: actions/setup-node@v2 
        with:
          node-version: '14'

      - name: check version
        run: node -v