name: My First Workflow
on: push
jobs:
  My_first_job_:
    runs-on: ubuntu-latest
    steps:
      - name: create a file
        run: echo "Hello, World!" > hello.txt
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-file
          path: hello.txt

  download_and_read:
    runs-on: [self-hosted, linux, x64,b14]
    needs: My_first_job_
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: hello-file
          path: .

      - name: read hello.txt
        run: cat hello.txt