name: My First Workflow
on: push
jobs:
  My_first_job_:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        run:  git clone https://github.com/desaipreeti/GithubActions.git

      - name: check files in Repo
        run: |
          cd GithubActions
          ls -la