name: My First Workflow
on: push
jobs:
  My_first_job_:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2


      - name: check files in Repo
        run: ls -la